# Site
title: Aayam's Homepage
description: Personal website showcasing my projects, research, and writing
lang: en
url: https://Mangrins.github.io
baseurl: ""

# Theme
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

# Author
author:
  name: Aayam Acharya
  email: aayamacharyaa@example.com

# Build
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: pretty

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

# Exclude
exclude:
  - README.md
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
